version: "3"

services:
  webserver:
    image: ghcr.io/simjanos-dev/linguacafe-webserver:latest
    depends_on:
      - database
    volumes:
      - storage:/var/www/html/storage
    environment:
      TZ: ${TIME_ZONE:-America/Sao_Paulo}
      # The database authentication and connection environment variables
      DB_DATABASE: ${LINGUACAFE_DB_DATABASE:-linguacafe}
      DB_USERNAME: ${LINGUACAFE_DB_USERNAME:-linguacafe}
      DB_PASSWORD: ${LINGUACAFE_DB_PASSWORD:-linguacafe}
    networks:
      linguacafe:
        aliases:
          - linguacafe-webserver
      traefik-public:

    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      labels:
        # Enable Traefik for this service, to make it available in the public network
        - traefik.enable=true
        # Use the traefik-public network
        - traefik.docker.network=traefik-public
        # Use the custom label "traefik.constraint-label=traefik-public"
        - traefik.constraint-label=traefik-public
        # traefik-https the actual router using HTTPS
        # Uses the environment variable BASE_DOMAIN
        - traefik.http.routers.linguacafe.rule=Host(`linguacafe.${BASE_DOMAIN?Variable not set}`)
        - traefik.http.routers.linguacafe.entrypoints=https
        - traefik.http.routers.linguacafe.tls=true
        # Serve the container on port 80
        - traefik.http.services.linguacafe.loadbalancer.server.port=80
        # Use the "le" (Let's Encrypt) resolver
        - traefik.http.routers.linguacafe.tls.certresolver=le

        # Homepage labels
        - homepage.group=Personal
        - homepage.name=LinguaCafe
        - homepage.icon=linguacafe.png
        - homepage.href=https://linguacafe.${BASE_DOMAIN?Variable not set}
        - homepage.description=Vocabulary & language learning

  database:
    image: mysql:8.0
    tty: true
    volumes:
      - database:/var/lib/mysql
    environment:
      TZ: ${TIME_ZONE:-America/Sao_Paulo}
      # The database authentication and connection environment variables
      MYSQL_DATABASE: ${LINGUACAFE_DB_DATABASE:-linguacafe}
      MYSQL_USER: ${LINGUACAFE_DB_USERNAME:-linguacafe}
      MYSQL_PASSWORD: ${LINGUACAFE_DB_PASSWORD:-linguacafe}
      MYSQL_ROOT_PASSWORD: ${LINGUACAFE_DB_ROOT_PASSWORD:-linguacafe}
      SERVICE_NAME: linguacafe
    command: mysqld --general-log=1 --general-log-file=/var/lib/mysql/general-log.log
    networks:
      linguacafe:
        aliases:
          - linguacafe-database

  python-service:
    image: ghcr.io/simjanos-dev/linguacafe-python-service:latest
    command: "python3 /app/tokenizer.py"
    tty: true
    environment:
      TZ: ${TIME_ZONE:-America/Sao_Paulo}
      PYTHONPATH: "/var/www/html/storage/app/model"
    volumes:
      - storage:/var/www/html/storage
    networks:
      linguacafe:
        aliases:
          - linguacafe-python-service

networks:
  # The internal linguacafe network
  linguacafe:
  # Use the previously created public network "traefik-public", shared with other
  # services and traefik, the service will be publicly available via Traefik
  traefik-public:
    external: true

volumes:
  # Create the volumes to store the linguacafe dabase and data, the volumes are saved on the NFS share
  # In specific, inside the linguacafe directory
  database:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=${NFS_IP?Variable not set},nolock,soft,rw
      device: ":${NFS_SHARE_PATH?Variable not set}/docker-swarm/linguacafe/database-volume"

  storage:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=${NFS_IP?Variable not set},nolock,soft,rw
      device: ":${NFS_SHARE_PATH?Variable not set}/docker-swarm/linguacafe/storage-volume"
